### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by tiagoarodrigues55** [Firebird1029/KhanSolver#1]
Hi bro, I was very interested in your project, could you explain me in more detail, what does it do? How to do?

**Comment by Firebird1029** [comment]
Hi! This was a quick project that can solve some Khan Academy math equations automatically by inspecting the underlying LaTeX and parsing it. Unfortunately, this extension is not "published" on the Chrome store but of course feel free to download the source code and play around with it if you wish!

**Comment by tiagoarodrigues55** [comment]
Thank you, very nice! I was curious because I also have a repository called khansolver, in my case I created a script to resolve all the user's recommendations. But I really liked your project, how do I use it?
